spring:
  application:
    name: goods-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/seata_demo?useUnicode=true&characterEncoding=UTF-8
server:
  port: 8082
mybatis-plus:
  type-handlers-package: com.lam.goods.converter