version: "3.8"

services:
  mysql:
    restart: always
    image: mysql:8.0.15
    container_name: mysqldb
    ports:
      - 3307:3306
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    restart: always
    image: redis:latest
    container_name: redisdb
    ports:
      - 6380:6379
  seata:
    restart: always
    image: seataio/seata-server:1.6.1
    container_name: seata
    hostname: seata-server
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
networks:
  default:
    name: "my-cloud-net"