version: "3.8"

services:
  nacos:
    restart: always
    image: nacos/nacos-server:v2.2.0
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9949:9949"
    environment:
      - JVM_XMS=512m
      - JVM_XMX=512m
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysqldb
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_NAME=nacos
    depends_on:
      - mysql
  mysql:
    restart: always
    image: mysql:8.0.15
    container_name: mysqldb
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  seata:
    depends_on:
      - mysql
    restart: always
    image: seataio/seata-server:1.6.1
    container_name: seata
    hostname: seata-server
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=db
    expose:
      - 8091
    volumes:
      - "./seata/application.yml:/seata-server/resources/application.yml"
networks:
  default:
    name: "seata-demo-net"